savq/paq-nvim

README.md
doc/paq-nvim.txt
lua/paq-nvim.lua

Since I neglected to create an issue before this PR, here is an overview of the changes.
`paq` has a new option called `as` which overrides `paq`'s name parsed from the repo. It also allows users to install plugins with the same name or otherwise ambiguous names (e.g. [dracula/vim](https://github.com/dracula/vim)).
This change was inspired by packer.nvim's `as` option.
This changes the way users install plugins from not-GitHub URLs to make it more intuitive. Currently, to install non-GitHub plugins a user must provide a pseudo-GitHub repo and then the full URL. This changes it so they provide the full URL and then the name of the plugin. So for example installing `https://example.com/vim-plugin.git`,
```lua
-- Old way with url
paq {'foo/vim-plugin', url = …
```

Add `as` option for aliases

---

lua/paq-nvim.lua

The call to `vim.list_extend` in `list_extend` didn't had the correct arguments, causing `:PaqInstall` to break.
Looks like PR#12 reused the code from `tbl_map`

Fix PaqInstall

---

lua/paq-nvim.lua

Just a workaround so nvim runs without errors.

GH-17 - Check `c` is valid before accessing in output_result()

---

doc/paq-nvim.txt
lua/paq-nvim.lua
plugin/paq-nvim.vim

This adds a `PaqList` command as proposed in Issue #21 that lists installed packages
as well as recently uninstalled ones. Packages that were recently installed or updated
are prefixed with a `+` and `*`, respectively. The formatting is currently 
```
Installed packages:
package1
+package2
*package3
...
Recently removed:
removed_package
...
```
but can be easily changed.
Changes are now tracked in the `changes` table which consists of `'name':'change'`
pairs, where `'change'` is either `'installed'`, `'updated'` or `'removed'`.
To update this table as well as the `packages[name].exists` fields on successful
installations and updates, the `call_proc`function now takes an optional callback function.
Since marking all packages as updated after running `PaqUpdate` is not very useful,
the …

Add a `PaqList` command

---

CHANGELOG.md
README.md
doc/paq-nvim.txt
lua/paq-nvim.lua
test/test.lua

The metamethod permits to use Paq with less boilerplate. It also correctly updates the list of packages when a configuration is re-sourced (no more problems with the Lua package's cache).
The old `paq` function still works.
TODO:
- ~update tests~
- update wiki

Add callable metamethod. Update docs

---

lua/paq-nvim.lua

Since the URL is later given to "git clone", the only thing we can
extract is the last path component, so that those two formats can be
supported:
https://git.sr.ht/~torresjrjr/gemini.vim
github.com:hello/my-private-project.git

Extract package name from its URL, if any

---

.gitignore
lua/paq.lua

- Fixes issue where PaqClean does nothing on windows #69 
- Fixes PaqClean deleting paq-nvim if user didn't have explicitly stated in `paq ' savq/paq-nvim'` #63

Fixes For PaqClean

---

lua/paq.lua

fix: use `vim.fn.environ` in nvim 0.5

---

lua/paq.lua

fix: use PascalCase for autocommand names

---

lua/paq.lua

fixes clean() behaviour - when scanning for directories to remove, the loop terminates immediately upon reaching paq-nvim, thus not all directories are always scanned and removed as necessary

fix clean() not scanning all directories

---

doc/paq-nvim.txt

Tiny typo of no significance whatsoever

remove extra t in htttps in url example

---

lua/paq.lua

When you call `PaqSync` and have a pinned package that has already been installed, paq will attempt to re-clone it and will throw an error since git will complain about the directory already existing. This PR fixes the issue.

fix: Don't try to clone existing pinned packages

---

README.md
doc/paq-nvim.txt

`hrsh7th/nvim-compe` was archived. The new repository is `hrsh7th/nvim-cmp`.

Update `hrsh7th/nvim-compe` to `hrsh7th/nvim-cmp`

---

lua/paq.lua

Adds the ability to add packages one at a time, as requested in #88. 
Honestly, I think it is better to load all plugins in a `plugins.lua` file, then create a `<plugin>.lua` file for the configuration of that plugin, but you could use this fork if need be.
```lua
local paq = require("paq")
paq.load("<package>")
```
Say you wanted to load [tpope/vim-surround](https://github.com/tpope/vim-surround), then you could do the following:
```lua
require("paq").load("tpope/vim-surround")
-- or
local paq = require("paq")
paq.load("tpope/vim-surround")
```

Add single line load() for adding packages

---

lua/paq.lua

Hello,
Neovim 0.8 has changed the default location of log files to `~/.local/state/nvim`: see https://github.com/neovim/neovim/issues/14090#issuecomment-1125055183. The issue is that the old log folder `~/.cache/nvim` is not created upon installation of Neovim 0.8 anymore so Paq would crash trying to write into it.
This PR updates the log file location accordingly while keeping backward compatibility.
(I also changed the case of logfile for consistency, I can revert this change if needed).

refactor: use new location for log files

---

lua/paq.lua

This pull request fixes #98 and fixes #112.
The issue is that when `counter` happens to get called for the last time by `run_hook`, the coroutine terminates and returns `nil`, rather than returning `true` which is expected from `coroutine.yield(true)`. Therefore, `run_hook` ends up returning `nil` [here](https://github.com/savq/paq-nvim/blob/b3c7d047e29792f306626bf87430a2b0c92e5aad/lua/paq.lua?plain=1#L89) which causes `counter` to be called again in `clone` [here](https://github.com/savq/paq-nvim/blob/b3c7d047e29792f306626bf87430a2b0c92e5aad/lua/paq.lua?plain=1#L114). This resumes a dead coroutine, hence the error.
This PR fixes this by returning `true` at the end of the coroutine, which seems to be the intended behavior.

Fix a bug in the counter coroutine

---

lua/paq.lua

Hi there,
Learned some libuv/luv
Re-implemented this feature using a table to place all outputs before write into log file.
Also added line breaking.
Here is the print of how it looks now. Please tell me if it should look different.
Or if code is not in pattern for this project.

Re-implement log updated packages commits fixing out of order bug.

---

lua/paq.lua

Enable using plain URLs directly, rather than needing to explicitly write {url="..."} for each one (which gets a bit noisy).
This enables the following usage:
```lua
require 'paq' {
"https://github.com/savq/paq-nvim",
}
```

Allow using URL as string

---

doc/paq-nvim.txt
lua/paq.lua

This make it so that if you use the method `opt` in the setup function all the packages will be installed by default in the opt directory, without specifying `opt = true` for all packages. Also if for whatever reason the user want some packages still in the start directory could pass `opt=false` and the package will be installed in the start directory.

feat: opt in setup function as default plugin location instead of start (#131)

---

doc/paq-nvim.txt
lua/paq.lua

Now opt should work as expected.

Fix issue #135

---

lua/paq.lua

Allows user to provide url_format config as following before requiring paq:
```lua
require('paq').setup {
-- Use SSH urls by default instead of HTTPS
url_format = 'git@github.com:%s.git'
}
```
Does not change the default from HTTPS nor interfere with user provided urls.

feat(#133): url-format

---

doc/paq-nvim.txt

Bootstrap script did not correctly identify if paq was installed It also did not create the exit autocommand before the event could trigger

Documentation change

---

README.md
doc/paq-nvim.txt
lua/paq.lua

fixes: #142
Now you can pass to the run function a string prepended with a `:` and will be run as a vim `:command`. This is actually how packer behave so this could be a nice to behave as the user expect.

feat: execute run hook as vim command if first char is ':'

---

lua/paq.lua

Related to: #107
This PR tries to implement a lockfile mechanism into Paq. The lockfile is stored in `stdpath('data')`, as a json file. The file tries to represent the previous state of Paq but since this cannot be trusted fully I've setup some safeguards that fall back to the previous behaviour when needed:
1. For cleaning up the packages I've maintained the previous function `find_unlisted()`. We cannot assume that all the unlisted packages will be listed in the lockfile.
2. If a lock file is not present it will not throw anything and generate itself from the current configuration.
This change is meant to be not disruptive and most users don't even need to know that is happening. Later in we can iterate over this feature and try to fix some of the bug and strange behaviour paq has (#99, …

feat: adding first implementation of a lockfile

---

lua/paq.lua

Quickfix for: #150
Removes all the run keys since they could contain a function and `json.encode` doesn't support encoding functions.

fix: remove run key before saving the state

---

.editorconfig
README.md
doc/paq-nvim.txt
lua/paq.lua

This PR does the following:
- adds `.editorconfig`: for better style consistency (supported natively in neovim 0.9)
- remove deprecated `paq` method
- now is required neovim 0.7 and above
- creates commands with lua api
- track status with Enum like table
- removing exists key
- created `filter` table to make it more easy filter packages
- iterating over lockfile functionality

Refactor code: Update minimum requirements to nvim 0.7

---

lua/paq.lua

The check to determine if a pkg was actually updated after a pull erroneously used the old pkg hash, even after pulling new commits. This pull request makes sure to use the new hash and also write it to the lock file.

fix: retrieve new hash after pull and write it to lock file (#160)

---

doc/paq-nvim.txt
lua/paq.lua

Related to: #164 
This little new method let's query paq's registry of packages to let the user have custom functionality like notify if the are packages to install at startup.
Notify user when there are new packages to install.
```lua
vim.api.nvim_create_autocmd("VimEnter", {
once = true,
callback = function() 
local pkgs_count = #require("paq").query("to_install")
if pkgs_count < 1 then return end
print(string.format("There are %d to install", pkgs_count))
end
})
```
You can even setup automatic packages installation at startup.
```lua
vim.api.nvim_create_autocmd("VimEnter", {
once = true,
callback = function() 
local pkgs_count = #require("paq").query("to_install")
if pkgs_count < 1 then return end
require("paq").install()
end
})
```

feat: adding query method to paq

---

lua/paq.lua

Fix: #166
Now in neovim nightly the uv module is called 'vim.uv' instead of 'vim.loop'. This coused some problems with some operations.

fix: error in nightly from renamed uv module

---

lua/paq.lua

Remappings of `G` should be ignored.

fix: use `normal!` with bang in `paq.log_open`

---

lua/paq.lua

Since `vim.notify` is just a wrapper of `nvim_echo()`, it cannot be used as `vim.system()` callback (vim.system() itself is also a wrapper of `vim.uv`). To solve it, I wrap it with `vim.schedule_wrap()`

fix: Fast API cannot be used in vim.system callback
